// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfJTA_AIH8rVPV2Jo6eCPX8BJE8JV-2fs',
    appId: '1:678520327474:android:3f0414f4f9f30d3637db2b',
    messagingSenderId: '678520327474',
    projectId: 'cine-ff4b1',
    storageBucket: 'cine-ff4b1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-aNFWE8zAgQ7_4PuJ2iIywztZVzWAt5A',
    appId: '1:678520327474:web:c581afc5093fa22637db2b',
    messagingSenderId: '678520327474',
    projectId: 'cine-ff4b1',
    authDomain: 'cine-ff4b1.firebaseapp.com',
    storageBucket: 'cine-ff4b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYJsOpUAaKWRBcjO1FVhBLI_bqN2V0Io',
    appId: '1:678520327474:ios:5da9112239b45e7237db2b',
    messagingSenderId: '678520327474',
    projectId: 'cine-ff4b1',
    storageBucket: 'cine-ff4b1.firebasestorage.app',
    androidClientId: '678520327474-7d5t9kv0nbhro13tf39eqi504vf90v6n.apps.googleusercontent.com',
    iosClientId: '678520327474-qhr3rim33kpqbci7peb7f5jkqsgd4bk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeWarriors',
  );

}